=== Futuray-pgm/mmo-data/Interface/Ui.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="http://www.w3schools.com/Ui"
    elementFormDefault="qualified"
    xmlns="http://www.w3schools.com/Ui"
    xmlns:mstns="http://www.w3schools.com/Ui.xsd"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
>
	<xs:simpleType name="FrameRendererType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="DefaultRenderer" />
			<xs:enumeration value="ButtonRenderer" />
			<xs:enumeration value="TextfieldRenderer" />
			<xs:enumeration value="ModelRenderer" />
			<xs:enumeration value="WorldRenderer" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="AnchorPointType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="LEFT" />
			<xs:enumeration value="TOP" />
			<xs:enumeration value="RIGHT" />
			<xs:enumeration value="BOTTOM" />
			<xs:enumeration value="H_CENTER" />
			<xs:enumeration value="V_CENTER" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="TilingType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="NONE" />
			<xs:enumeration value="HORZ" />
			<xs:enumeration value="VERT" />
			<xs:enumeration value="BOTH" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="HorzAlignType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="LEFT" />
			<xs:enumeration value="CENTER" />
			<xs:enumeration value="RIGHT" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="VertAlignType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="TOP" />
			<xs:enumeration value="CENTER" />
			<xs:enumeration value="BOTTOM" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="PropertyType">
		<xs:attribute name="name" use="required" type="xs:string" />
		<xs:attribute name="value" use="optional" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="BorderComponentType">
		<xs:sequence minOccurs="0" maxOccurs="1">
			<xs:element name="Area" type="AreaComponentType" maxOccurs="1" />
		</xs:sequence>

		<xs:attribute name="texture" use="optional" type="xs:string" />
		<xs:attribute name="borderSize" use="required" type="xs:decimal" />
	</xs:complexType>

	<xs:complexType name="ImageComponentType">
		<xs:sequence minOccurs="0" maxOccurs="1">
			<xs:element name="Area" type="AreaComponentType" maxOccurs="1" />
		</xs:sequence>

		<xs:attribute name="texture" use="optional" type="xs:string" />
		<xs:attribute name="tint" use="optional" type="xs:string" default="ffffffff" />
		<xs:attribute name="tiling" use="optional" type="TilingType" default="NONE" />
	</xs:complexType>

	<xs:complexType name="TextComponentType">
		<xs:sequence minOccurs="0" maxOccurs="1">
			<xs:element name="Area" type="AreaComponentType" maxOccurs="1" />
		</xs:sequence>

		<xs:attribute name="color" use="optional" type="xs:string" default="ffffffff" />
		<xs:attribute name="horzAlign" use="optional" type="HorzAlignType" default="LEFT" />
		<xs:attribute name="vertAlign" use="optional" type="VertAlignType" default="TOP" />
	</xs:complexType>

	<xs:complexType name="ImagerySectionType">
		<xs:sequence>
			<xs:choice maxOccurs="unbounded">
				<xs:element name="BorderComponent" type="BorderComponentType" />
				<xs:element name="ImageComponent" type="ImageComponentType" />
				<xs:element name="TextComponent" type="TextComponentType" />
			</xs:choice>
		</xs:sequence>
		<xs:attribute name="name" use="required" type="xs:string" />
	</xs:complexType>
	
	<xs:complexType name="SectionType">
		<xs:attribute name="section" use="required" type="xs:string" />
	</xs:complexType>
	
	<xs:complexType name="LayerType">
		<xs:sequence>
			<xs:element name="Section" maxOccurs="unbounded" minOccurs="1" type="SectionType" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="StateImageryType">
		<xs:sequence maxOccurs="unbounded">
			<xs:element name="Layer" type="LayerType" minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>

		<xs:attribute name="name" use="required" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="VisualType">
		<xs:sequence minOccurs="0">
			<xs:choice maxOccurs="unbounded">
				<xs:element name="ImagerySection" maxOccurs="unbounded" type="ImagerySectionType" />
				<xs:element name="StateImagery" maxOccurs="unbounded" type="StateImageryType" />
			</xs:choice>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="SizeType">
		<xs:sequence>
			<xs:element name="AbsDimension">
				<xs:complexType>
					<xs:attribute name="x" use="optional" type="xs:decimal" />
					<xs:attribute name="y" use="optional" type="xs:decimal" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="AnchorType">
		<xs:attribute name="point" use="required" type="AnchorPointType" />
		<xs:attribute name="targetPoint" use="optional" type="AnchorPointType" />
		<xs:attribute name="relativeTo" use="optional" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="InsetType">
		<xs:attribute name="all" use="optional" type="xs:decimal" />
		<xs:attribute name="left" use="optional" type="xs:decimal" />
		<xs:attribute name="top" use="optional" type="xs:decimal" />
		<xs:attribute name="right" use="optional" type="xs:decimal" />
		<xs:attribute name="bottom" use="optional" type="xs:decimal" />
	</xs:complexType>

	<xs:complexType name="AreaComponentType">
		<xs:sequence>
			<xs:choice>
				<xs:element name="Inset" type="InsetType" />
			</xs:choice>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="AreaType">
		<xs:sequence>
			<xs:choice>
				<xs:element name="Size" type="SizeType" maxOccurs="1" />
				<xs:element name="Anchor" type="AnchorType" maxOccurs="6" />
			</xs:choice>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="FrameType">
		<xs:sequence>
			<xs:choice maxOccurs="unbounded">
				<xs:element name="Property" type="PropertyType" maxOccurs="unbounded" />
				<xs:element name="Visual" type="VisualType" maxOccurs="1" />
				<xs:element name="Area" maxOccurs="1" type="AreaType" />
				<xs:element name="Events" maxOccurs="1"  />
			</xs:choice>
		</xs:sequence>

		<xs:attribute name="name" type="xs:string" use="required" />
		<xs:attribute name="renderer" type="FrameRendererType" use="optional" />
	</xs:complexType>

	<xs:element name="Frame" type="FrameType" />

	<xs:element name="UiLayout">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Script" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="file" type="xs:string" use="required" />
					</xs:complexType>
				</xs:element>
				<xs:element ref="Frame" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Futuray-pgm/mmo-data/Interface/GameUI/LootFrame.xml
<?xml version="1.0" ?>
<UiLayout xmlns="http://www.w3schools.com/Ui" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com/Ui.xsd file:///F:/mmo/data/client/Interface/Ui.xsd">
	<Script file="LootFrame.lua" />
	
    <Frame name="LootButtonTemplate" type="Button" renderer="ButtonRenderer">
        <Property name="Icon" />

        <Visual>
			<ImagerySection name="Image">
				<ImageComponent>
					<Area>
						<Inset all="16" />
					</Area>
					<PropertyValue property="Icon" />
				</ImageComponent>
			</ImagerySection>
			<ImagerySection name="Text">
				<TextComponent horzAlign="RIGHT" vertAlign="BOTTOM">
					<Area>
						<Inset all="8" />
					</Area>
				</TextComponent>
			</ImagerySection>
			<ImagerySection name="NormalFrame">
				<BorderComponent texture="Interface/BW_ButtonSmall_Up.htex" borderSize="30" />
			</ImagerySection>
			<ImagerySection name="HoveredFrame">
				<BorderComponent texture="Interface/BW_ButtonSmall_Over.htex" borderSize="30" />
			</ImagerySection>
			<ImagerySection name="PushedFrame">
				<BorderComponent texture="Interface/BW_ButtonSmall_Down.htex" borderSize="30" />
			</ImagerySection>
			<ImagerySection name="DisabledFrame">
				<BorderComponent texture="Interface/BW_ButtonSmall_Up.htex" borderSize="30" />
			</ImagerySection>
			<StateImagery name="Normal">
				<Layer>
					<Section section="NormalFrame" />
					<Section section="Image" />
					<Section section="Text" />
				</Layer>
			</StateImagery>
			<StateImagery name="Hovered">
				<Layer>
					<Section section="HoveredFrame" />
					<Section section="Image" />
					<Section section="Text" />
				</Layer>
			</StateImagery>
			<StateImagery name="Pushed">
				<Layer>
					<Section section="PushedFrame" />
					<Section section="Image" />
					<Section section="Text" />
				</Layer>
			</StateImagery>
			<StateImagery name="Disabled">
				<Layer>
					<Section section="DisabledFrame" />
					<Section section="Image" />
					<Section section="Text" />
				</Layer>
			</StateImagery>
		</Visual>

		<Area>
			<Size>
				<AbsDimension x="128" y="128" />
			</Size>
		</Area>
    </Frame>

    <Frame name="LootFrame" parent="GameParent" renderer="DefaultRenderer">
        <Property name="Visible" value="false" />

		<Visual>
			<ImagerySection name="Background">
				<BorderComponent texture="Interface/GameUI/fg4_borders_01_03.htex" borderSize="250" />
			</ImagerySection>
			<StateImagery name="Enabled">
				<Layer>
					<Section section="Background" />
				</Layer>
			</StateImagery>
		</Visual>

		<Scripts>
			<OnLoad>
				return function(self)
					LootFrame_OnLoad(self);
				end
			</OnLoad>
			<OnShow>
				return function(self)
					LootFrame_OnShow(self);
				end
			</OnShow>
			<OnHide>
				return function(self)
					LootFrame_OnHide(self);
				end
			</OnHide>
			<OnUpdate>
				return function(self, elapsed)
					LootFrame_OnUpdate(self, elapsed);
				end
			</OnUpdate>
		</Scripts>

		<Area>
			<Size><AbsDimension x="640" y="640" /></Size>
			<Anchor point="LEFT" offset="0" />
			<Anchor point="TOP" offset="300" />
		</Area>

        <Frame name="LootButton1" inherits="LootButtonTemplate" id="1">
            <Area>
                <Anchor point="LEFT" offset="64" />
                <Anchor point="TOP" offset="64" />
            </Area>
        </Frame>

        <Frame name="LootText1" inherits="TextSmall" id="1">
            <Area>
                <Anchor point="TOP" relativeTo="LootButton1" offset="0" />
                <Anchor point="LEFT" relativePoint="RIGHT" relativeTo="LootButton1" offset="0" />
                <Anchor point="RIGHT" />
                <Anchor point="BOTTOM" relativeTo="LootButton1" offset="0" />
            </Area>
        </Frame>

        <Frame name="LootButton2" inherits="LootButtonTemplate" id="2">
            <Area>
                <Anchor point="LEFT" relativeTo="LootButton1" />
                <Anchor point="TOP" offset="0" relativePoint="BOTTOM" relativeTo="LootButton1" />
            </Area>
        </Frame>

        <Frame name="LootText2" inherits="TextSmall" id="2">
            <Area>
                <Anchor point="TOP" relativeTo="LootButton2" offset="0" />
                <Anchor point="LEFT" relativePoint="RIGHT" relativeTo="LootButton2" offset="0" />
                <Anchor point="RIGHT" />
                <Anchor point="BOTTOM" relativeTo="LootButton2" offset="0" />
            </Area>
        </Frame>

        <Frame name="LootButton3" inherits="LootButtonTemplate" id="3">
            <Area>
                <Anchor point="LEFT" relativeTo="LootButton2" />
                <Anchor point="TOP" offset="0" relativePoint="BOTTOM" relativeTo="LootButton2" />
            </Area>
        </Frame>

        <Frame name="LootText3" inherits="TextSmall" id="3">
            <Area>
                <Anchor point="TOP" relativeTo="LootButton3" offset="0" />
                <Anchor point="LEFT" relativePoint="RIGHT" relativeTo="LootButton3" offset="0" />
                <Anchor point="RIGHT" />
                <Anchor point="BOTTOM" relativeTo="LootButton3" offset="0" />
            </Area>
        </Frame>

        <Frame name="LootButton4" inherits="LootButtonTemplate" id="4">
            <Area>
                <Anchor point="LEFT" relativeTo="LootButton3" />
                <Anchor point="TOP" offset="0" relativePoint="BOTTOM" relativeTo="LootButton3" />
            </Area>
        </Frame>
		
        <Frame name="LootText4" inherits="TextSmall" id="4">
            <Area>
                <Anchor point="TOP" relativeTo="LootButton4" offset="0" />
                <Anchor point="LEFT" relativePoint="RIGHT" relativeTo="LootButton4" offset="0" />
                <Anchor point="RIGHT" />
                <Anchor point="BOTTOM" relativeTo="LootButton4" offset="0" />
            </Area>
        </Frame>

	</Frame>
</UiLayout>

=== Futuray-pgm/mmo-data/Interface/GameUI/GameMenuBar.xml
<?xml version="1.0" ?>
<UiLayout xmlns="http://www.w3schools.com/Ui" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com/Ui.xsd file:///F:/mmo/data/client/Interface/Ui.xsd">
	<Script file="GameMenuBar.lua" />
	
	<Frame name="GameMenuBarImageButton" type="Button" renderer="ButtonRenderer">
		<Property name="Icon" />

		<Visual>
			<ImagerySection name="Image">
				<ImageComponent>
					<Area>
						<Inset all="8" />
					</Area>
					<PropertyValue property="Icon" />
				</ImageComponent>
			</ImagerySection>
			<ImagerySection name="NormalFrame">
				<BorderComponent texture="Interface/GlueUI/ButtonNormal.htex" borderSize="30" />
			</ImagerySection>
			<ImagerySection name="HoveredFrame">
				<BorderComponent texture="Interface/GlueUI/ButtonHovered.htex" borderSize="30" />
			</ImagerySection>
			<ImagerySection name="PushedFrame">
				<BorderComponent texture="Interface/GlueUI/ButtonPushed.htex" borderSize="30" />
			</ImagerySection>
			<ImagerySection name="DisabledFrame">
				<BorderComponent texture="Interface/GlueUI/ButtonDisabled.htex" borderSize="30" />
			</ImagerySection>
			<StateImagery name="Normal">
				<Layer>
					<Section section="NormalFrame" />
					<Section section="Image" />
				</Layer>
			</StateImagery>
			<StateImagery name="Hovered">
				<Layer>
					<Section section="HoveredFrame" />
					<Section section="Image" />
				</Layer>
			</StateImagery>
			<StateImagery name="Pushed">
				<Layer>
					<Section section="PushedFrame" />
					<Section section="Image" />
				</Layer>
			</StateImagery>
			<StateImagery name="Disabled">
				<Layer>
					<Section section="DisabledFrame" />
					<Section section="Image" />
				</Layer>
			</StateImagery>
		</Visual>
		<Area>
			<Size>
				<AbsDimension x="128" y="128" />
			</Size>
		</Area>
	</Frame>

	<Frame name="GameMenuBarButtonTemplate" inherits="GlueButton">
		<Area>
			<Size><AbsDimension x="400" y="96"/></Size>
			<Anchor point="LEFT" offset="16" />
		</Area>
	</Frame>

	<Frame name="GameMenuBar" renderer="DefaultRenderer" parent="GameParent">
		<!--<Visual>
			<ImagerySection name="Background">
				<ImageComponent texture="Interface/GameUI/fg4_borders_stone_bg_01_result.htex" tiling="BOTH">
					<Area><Inset all="8" /></Area>
				</ImageComponent>
				<BorderComponent texture="Interface/GameUI/fg4_borders_stone_edges_result.htex" borderSize="45" />
			</ImagerySection>
			<StateImagery name="Enabled">
				<Layer>
					<Section section="Background" />
				</Layer>
			</StateImagery>
		</Visual>-->

		<!--
		<Frame name="GameMenuBarTLFrame" renderer="DefaultRenderer">
			<Visual>
				<ImagerySection name="Background">
					<ImageComponent texture="Interface/GameUI/fg4_borders_01_14.htex" tiling="NONE" />
				</ImagerySection>
				<StateImagery name="Enabled">
					<Layer>
						<Section section="Background" />
					</Layer>
				</StateImagery>
			</Visual>
				
			<Area>
				<Size><AbsDimension x="48" y="48" /></Size>
				<Anchor point="TOP" offset="0" />
				<Anchor point="LEFT" offset="0" />
			</Area>
		</Frame>

		<Frame name="GameMenuBarTRFrame" renderer="DefaultRenderer">
			<Visual>
				<ImagerySection name="Background">
					<ImageComponent texture="Interface/GameUI/fg4_borders_01_14-05.htex" tiling="NONE" />
				</ImagerySection>
				<StateImagery name="Enabled">
					<Layer>
						<Section section="Background" />
					</Layer>
				</StateImagery>
			</Visual>
				
			<Area>
				<Size><AbsDimension x="48" y="48" /></Size>
				<Anchor point="TOP" offset="0" />
				<Anchor point="RIGHT" offset="0" />
			</Area>
		</Frame>
		-->
		
		<Area>
			<Size><AbsDimension y="96" /></Size>
			<Anchor point="BOTTOM" offset="0" />
			<Anchor point="LEFT" offset="0" />
			<Anchor point="RIGHT" offset="0" />
		</Area>
	</Frame>
</UiLayout>

=== Futuray-pgm/mmo-data/Interface/GameUI/GameTooltip.xml
<?xml version="1.0" ?>
<UiLayout xmlns="http://www.w3schools.com/Ui" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com/Ui.xsd file:///F:/mmo/data/client/Interface/Ui.xsd">
	<Script file="GameTooltip.lua" />
	
	<Font name="TooltipTitleFont" file="Fonts/ARIALN.TTF" size="32" outline="0" />
	<Font name="TooltipFont" file="Fonts/ARIALN.TTF" size="26" outline="0" />

    <Frame name="GameTooltipLineTemplate" renderer="DefaultRenderer">
		<Property name="Font" value="TooltipFont" />

        <Visual>
			<ImagerySection name="Text">
				<TextComponent color="FFFFFFFF" horzAlign="LEFT" />
            </ImagerySection>

			<StateImagery name="Enabled">
				<Layer>
					<Section section="Text" />
				</Layer>
			</StateImagery>
			<StateImagery name="Disabled">
				<Layer>
					<Section section="Text" />
				</Layer>
			</StateImagery>
        </Visual>
        <Area>
            <Size><AbsDimension x="512" y="32" /></Size>
        </Area>
    </Frame>
    
    <Frame name="GameTooltip" renderer="DefaultRenderer" parent="GameParent">
		<Visual>
			<ImagerySection name="Background">
				<ImageComponent texture="Interface/GlueUI/TransparentBorder.htex" tiling="NONE">
					<Area><Inset all="8" /></Area>
                </ImageComponent>
				<BorderComponent texture="Interface/GameUI/fg4_borders_stone_edges_result.htex" borderSize="32" />
			</ImagerySection>
			<StateImagery name="Enabled">
				<Layer>
					<Section section="Background" />
				</Layer>
			</StateImagery>
		</Visual>

        <Frame name="GameTooltipTitle" inherits="TextSmall">
            <Property name="Font" value="TooltipTitleFont" />
            <Property name="Text" value="TITLE" />

            <Area>
                <Size><AbsDimension y="32" /></Size>
                <Anchor point="TOP" offset="16" />
                <Anchor point="LEFT" offset="16" />
                <Anchor point="RIGHT" offset="-16" />
            </Area>
        </Frame>

        <Frame name="GameTooltipLines">
            <Area>
                <Anchor point="TOP" relativePoint="BOTTOM" relativeTo="GameTooltipTitle" offset="8" />
                <Anchor point="LEFT" relativeTo="GameTooltipTitle" />
                <Anchor point="RIGHT" relativeTo="GameTooltipTitle" />
                <Anchor point="BOTTOM" offset="-8" />
            </Area>
        </Frame>

		<Area>
			<Size><AbsDimension x="540" y="96" /></Size>
			<Anchor point="RIGHT" offset="-64" />
			<Anchor point="BOTTOM" offset="-64" />
		</Area>
	</Frame>
</UiLayout>

=== Futuray-pgm/mmo-data/Interface/GameUI/CastBar.xml
<?xml version="1.0" ?>
<UiLayout xmlns="http://www.w3schools.com/Ui" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com/Ui.xsd file:///F:/mmo/data/client/Interface/Ui.xsd">
	<Script file="CastBar.lua" />

    <Frame name="PlayerCastBar" type="ProgressBar" parent="GameParent">
        <Property name="Progress" value="0.12783" />
        <Property name="Text" value="SPELL_NAME" />
        <Property name="Font" value="DefaultSmall" />
		<Property name="Visible" value="False" />

        <Area>
            <Anchor point="H_CENTER" />
            <Anchor point="BOTTOM" offset="-400" />
            <Size><AbsDimension x="400" y="48" /></Size>
        </Area>

        <Visual>
            <ImagerySection name="Caption">
                <TextComponent color="FFFFFFFF" horzAlign="CENTER" vertAlign="CENTER" />
            </ImagerySection>
            <ImagerySection name="Background">
                <BorderComponent texture="Interface/fg4_borders_01_33.htex" borderSize="5" />
            </ImagerySection>
            <ImagerySection name="Border">
                <BorderComponent texture="Interface/GameUI/fg4_borders_insetBlack.htex" borderSize="24" />
            </ImagerySection>
            <ImagerySection name="Progress">
                <ImageComponent texture="Interface/fg4_gradientWhiteV1_result.htex" tiling="HORZ" tint="FF888800">
                    <Area><Inset all="8" /></Area>
                </ImageComponent>
            </ImagerySection>

            <StateImagery name="Enabled">
                <Layer>
                    <Section section="Background" />
                </Layer>
            </StateImagery>
            <StateImagery name="Disabled">
                <Layer>
                    <Section section="Background" />
                </Layer>
            </StateImagery>
            <StateImagery name="Progress">
                <Layer>
                    <Section section="Progress" />
                </Layer>
            </StateImagery>
            <StateImagery name="Overlay">
                <Layer>
                    <Section section="Border" />
                    <Section section="Caption" />
                </Layer>
            </StateImagery>
        </Visual>
        
		<Scripts>
			<OnLoad>
				return function(this)
					CastBar_OnLoad(this);
				end
			</OnLoad>
			<OnUpdate>
				return function(this, elapsed)
					CastBar_OnUpdate(this, elapsed);
				end
			</OnUpdate>
		</Scripts>
    </Frame>
</UiLayout>

=== Futuray-pgm/mmo-data/Interface/GameUI/SpellBook.xml
<?xml version="1.0" ?>
<UiLayout xmlns="http://www.w3schools.com/Ui" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com/Ui.xsd file:///F:/mmo/data/client/Interface/Ui.xsd">
	<Script file="SpellBook.lua" />

	<Frame name="SpellBookButtonTemplate" type="Button" renderer="ButtonRenderer">
		<Property name="Icon" />

		<Visual>
			<ImagerySection name="Image">
				<ImageComponent>
					<Area>
						<Inset all="16" />
					</Area>
					<PropertyValue property="Icon" />
				</ImageComponent>
			</ImagerySection>
			<ImagerySection name="NormalFrame">
				<BorderComponent texture="Interface/BW_ButtonSmall_Up.htex" borderSize="30" />
			</ImagerySection>
			<ImagerySection name="HoveredFrame">
				<BorderComponent texture="Interface/BW_ButtonSmall_Over.htex" borderSize="30" />
			</ImagerySection>
			<ImagerySection name="PushedFrame">
				<BorderComponent texture="Interface/BW_ButtonSmall_Down.htex" borderSize="30" />
			</ImagerySection>
			<ImagerySection name="DisabledFrame">
				<BorderComponent texture="Interface/BW_ButtonSmall_Up.htex" borderSize="30" />
			</ImagerySection>
			<StateImagery name="Normal">
				<Layer>
					<Section section="NormalFrame" />
					<Section section="Image" />
				</Layer>
			</StateImagery>
			<StateImagery name="Hovered">
				<Layer>
					<Section section="HoveredFrame" />
					<Section section="Image" />
				</Layer>
			</StateImagery>
			<StateImagery name="Pushed">
				<Layer>
					<Section section="PushedFrame" />
					<Section section="Image" />
				</Layer>
			</StateImagery>
			<StateImagery name="Disabled">
				<Layer>
					<Section section="DisabledFrame" />
					<Section section="Image" />
				</Layer>
			</StateImagery>
		</Visual>

        <Frame name="NameLabel" inherits="TextSmall">
            <Property name="Text" value="Spell" />
                
            <Area>
                <Anchor point="TOP" />
                <Anchor point="LEFT" offset="128" />
                <Size><AbsDimension x="128" y="32" /></Size>
            </Area>
        </Frame>

        <Frame name="SubLabel" inherits="TextSmall">
            <Property name="Text" value="Rank 1" />
            
            <Area>
                <Anchor point="TOP" relativeTo="NameLabel" relativePoint="BOTTOM" />
                <Anchor point="LEFT" offset="128" />
                <Size><AbsDimension x="128" y="32" /></Size>
            </Area>
        </Frame>

		<Area>
			<Size>
				<AbsDimension x="128" y="128" />
			</Size>
		</Area>
	</Frame>

    <Frame name="SpellBook" renderer="DefaultRenderer" parent="GameParent">
		<Visual>
			<ImagerySection name="Background">
				<BorderComponent texture="Interface/GameUI/fg4_borders_01_03.htex" borderSize="250" />
			</ImagerySection>
			<StateImagery name="Enabled">
				<Layer>
					<Section section="Background" />
				</Layer>
			</StateImagery>
		</Visual>

        <Area>
			<Size><AbsDimension x="960" y="1280" /></Size>
            <Anchor point="LEFT" offset="32" />
            <Anchor point="TOP" offset="256" />
        </Area>

		<Frame name="SpellBookTitleBar" inherits="TitleBar">
			<Property name="Text" value="SPELLBOOK" />

			<Area>
				<Anchor point="TOP" offset="62" />
				<Anchor point="LEFT" offset="48" />
				<Anchor point="RIGHT" offset="-48" />
			</Area>
		</Frame>

        <Frame inherits="SpellBookButtonTemplate" name="SpellBookButton01">
            <Property name="Icon" value="Interface/Icons/Spells/S_Attack.htex" />
            <Area>
                <Anchor point="TOP" relativeTo="SpellBookTitleBar" relativePoint="BOTTOM" offset="16" />
                <Anchor point="LEFT" offset="64" />
            </Area>
        </Frame>

        <Frame inherits="SpellBookButtonTemplate" name="SpellBookButton02">
            <Property name="Icon" value="Interface/Icons/Spells/S_Fireball.htex" />
            <Area>
                <Anchor point="TOP" relativeTo="SpellBookButton01" />
                <Anchor point="LEFT" relativePoint="H_CENTER" offset="16" />
            </Area>
        </Frame>

        <Frame inherits="SpellBookButtonTemplate" name="SpellBookButton03">
            <Property name="Icon" value="Interface/Icons/Spells/S_FrostBolt.htex" />
            <Area>
                <Anchor point="TOP" relativePoint="BOTTOM" relativeTo="SpellBookButton01" offset="16" />
                <Anchor point="LEFT" relativeTo="SpellBookButton01" />
            </Area>
        </Frame>

        <Frame inherits="SpellBookButtonTemplate" name="SpellBookButton04">
            <Area>
                <Anchor point="TOP" relativeTo="SpellBookButton03" />
                <Anchor point="LEFT" relativeTo="SpellBookButton02" />
            </Area>
        </Frame>

        <Scripts>
            <OnLoad>
                return function(this)
                    SpellBook_OnLoad()
                end
            </OnLoad>
        </Scripts>
    </Frame>
</UiLayout>

=== Futuray-pgm/mmo-data/Interface/GameUI/GameMenu.xml
<?xml version="1.0" ?>
<UiLayout xmlns="http://www.w3schools.com/Ui" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com/Ui.xsd file:///F:/mmo/data/client/Interface/Ui.xsd">
	<Script file="GameMenu.lua" />
	
	<Frame name="GameMenuButtonTemplate" inherits="GlueButton">
		<Area>
			<Anchor point="LEFT" offset="16" />
			<Anchor point="RIGHT" offset="-16" />
			<Size><AbsDimension x="440" y="112" /></Size>
		</Area>
	</Frame>

	<Frame name="GameMenu" renderer="DefaultRenderer" parent="GameParent">
		<Property name="Visible" value="False" />

		<Visual>
			<ImagerySection name="Background">
				<BorderComponent texture="Interface/GameUI/fg4_borders_01_03.htex" borderSize="250" />
			</ImagerySection>
			<StateImagery name="Enabled">
				<Layer>
					<Section section="Background" />
				</Layer>
			</StateImagery>
		</Visual>


		<Area>
			<Size><AbsDimension x="540" y="128" /></Size>
			<Anchor point="H_CENTER" />
			<Anchor point="V_CENTER" />
		</Area>

		<Frame name="MenuTitleBar" inherits="TitleBar">
			<Property name="Text" value="MENU" />

			<Area>
				<Anchor point="TOP" offset="62" />
				<Anchor point="LEFT" offset="48" />
				<Anchor point="RIGHT" offset="-48" />
			</Area>
		</Frame>

		<Frame name="GameMenuButtons" renderer="DefaultRenderer">
			<Visual>
				<ImagerySection name="Border">
					<BorderComponent texture="Interface/GameUI/fg4_borders_01_19.htex" borderSize="25" />
				</ImagerySection>
				<StateImagery name="Enabled">
					<Layer>
						<Section section="Border" />
					</Layer>
				</StateImagery>
			</Visual>

			<Area>
				<Anchor point="TOP" relativePoint="BOTTOM" relativeTo="MenuTitleBar" offset="5" />
				<Anchor point="LEFT" offset="48" />
				<Anchor point="RIGHT" offset="-48" />
				<Anchor point="BOTTOM" offset="-48" />
			</Area>
		</Frame>
		
		<Scripts>
			<OnLoad>
				return function(self)
					GameMenu_OnLoad(self);
				end
			</OnLoad>
		</Scripts>
	</Frame>
</UiLayout>
