=== Futuray-pgm/mmo-data/Interface/Ui.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="http://www.w3schools.com/Ui"
    elementFormDefault="qualified"
    xmlns="http://www.w3schools.com/Ui"
    xmlns:mstns="http://www.w3schools.com/Ui.xsd"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
>
	<xs:simpleType name="FrameRendererType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="DefaultRenderer" />
			<xs:enumeration value="ButtonRenderer" />
			<xs:enumeration value="TextfieldRenderer" />
			<xs:enumeration value="ModelRenderer" />
			<xs:enumeration value="WorldRenderer" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="AnchorPointType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="LEFT" />
			<xs:enumeration value="TOP" />
			<xs:enumeration value="RIGHT" />
			<xs:enumeration value="BOTTOM" />
			<xs:enumeration value="H_CENTER" />
			<xs:enumeration value="V_CENTER" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="TilingType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="NONE" />
			<xs:enumeration value="HORZ" />
			<xs:enumeration value="VERT" />
			<xs:enumeration value="BOTH" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="HorzAlignType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="LEFT" />
			<xs:enumeration value="CENTER" />
			<xs:enumeration value="RIGHT" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="VertAlignType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="TOP" />
			<xs:enumeration value="CENTER" />
			<xs:enumeration value="BOTTOM" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="PropertyType">
		<xs:attribute name="name" use="required" type="xs:string" />
		<xs:attribute name="value" use="optional" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="BorderComponentType">
		<xs:sequence minOccurs="0" maxOccurs="1">
			<xs:element name="Area" type="AreaComponentType" maxOccurs="1" />
		</xs:sequence>

		<xs:attribute name="texture" use="optional" type="xs:string" />
		<xs:attribute name="borderSize" use="required" type="xs:decimal" />
	</xs:complexType>

	<xs:complexType name="ImageComponentType">
		<xs:sequence minOccurs="0" maxOccurs="1">
			<xs:element name="Area" type="AreaComponentType" maxOccurs="1" />
		</xs:sequence>

		<xs:attribute name="texture" use="optional" type="xs:string" />
		<xs:attribute name="tint" use="optional" type="xs:string" default="ffffffff" />
		<xs:attribute name="tiling" use="optional" type="TilingType" default="NONE" />
	</xs:complexType>

	<xs:complexType name="TextComponentType">
		<xs:sequence minOccurs="0" maxOccurs="1">
			<xs:element name="Area" type="AreaComponentType" maxOccurs="1" />
		</xs:sequence>

		<xs:attribute name="color" use="optional" type="xs:string" default="ffffffff" />
		<xs:attribute name="horzAlign" use="optional" type="HorzAlignType" default="LEFT" />
		<xs:attribute name="vertAlign" use="optional" type="VertAlignType" default="TOP" />
	</xs:complexType>

	<xs:complexType name="ImagerySectionType">
		<xs:sequence>
			<xs:choice maxOccurs="unbounded">
				<xs:element name="BorderComponent" type="BorderComponentType" />
				<xs:element name="ImageComponent" type="ImageComponentType" />
				<xs:element name="TextComponent" type="TextComponentType" />
			</xs:choice>
		</xs:sequence>
		<xs:attribute name="name" use="required" type="xs:string" />
	</xs:complexType>
	
	<xs:complexType name="SectionType">
		<xs:attribute name="section" use="required" type="xs:string" />
	</xs:complexType>
	
	<xs:complexType name="LayerType">
		<xs:sequence>
			<xs:element name="Section" maxOccurs="unbounded" minOccurs="1" type="SectionType" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="StateImageryType">
		<xs:sequence maxOccurs="unbounded">
			<xs:element name="Layer" type="LayerType" minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>

		<xs:attribute name="name" use="required" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="VisualType">
		<xs:sequence minOccurs="0">
			<xs:choice maxOccurs="unbounded">
				<xs:element name="ImagerySection" maxOccurs="unbounded" type="ImagerySectionType" />
				<xs:element name="StateImagery" maxOccurs="unbounded" type="StateImageryType" />
			</xs:choice>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="SizeType">
		<xs:sequence>
			<xs:element name="AbsDimension">
				<xs:complexType>
					<xs:attribute name="x" use="optional" type="xs:decimal" />
					<xs:attribute name="y" use="optional" type="xs:decimal" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="AnchorType">
		<xs:attribute name="point" use="required" type="AnchorPointType" />
		<xs:attribute name="targetPoint" use="optional" type="AnchorPointType" />
		<xs:attribute name="relativeTo" use="optional" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="InsetType">
		<xs:attribute name="all" use="optional" type="xs:decimal" />
		<xs:attribute name="left" use="optional" type="xs:decimal" />
		<xs:attribute name="top" use="optional" type="xs:decimal" />
		<xs:attribute name="right" use="optional" type="xs:decimal" />
		<xs:attribute name="bottom" use="optional" type="xs:decimal" />
	</xs:complexType>

	<xs:complexType name="AreaComponentType">
		<xs:sequence>
			<xs:choice>
				<xs:element name="Inset" type="InsetType" />
			</xs:choice>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="AreaType">
		<xs:sequence>
			<xs:choice>
				<xs:element name="Size" type="SizeType" maxOccurs="1" />
				<xs:element name="Anchor" type="AnchorType" maxOccurs="6" />
			</xs:choice>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="FrameType">
		<xs:sequence>
			<xs:choice maxOccurs="unbounded">
				<xs:element name="Property" type="PropertyType" maxOccurs="unbounded" />
				<xs:element name="Visual" type="VisualType" maxOccurs="1" />
				<xs:element name="Area" maxOccurs="1" type="AreaType" />
				<xs:element name="Events" maxOccurs="1"  />
			</xs:choice>
		</xs:sequence>

		<xs:attribute name="name" type="xs:string" use="required" />
		<xs:attribute name="renderer" type="FrameRendererType" use="optional" />
	</xs:complexType>

	<xs:element name="Frame" type="FrameType" />

	<xs:element name="UiLayout">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Script" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="file" type="xs:string" use="required" />
					</xs:complexType>
				</xs:element>
				<xs:element ref="Frame" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Futuray-pgm/mmo-data/Interface/GameUI/CharacterWindow.xml
<?xml version="1.0" ?>
<UiLayout xmlns="http://www.w3schools.com/Ui" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com/Ui.xsd file:///F:/mmo/data/client/Interface/Ui.xsd">
	<Script file="CharacterWindow.lua" />
	
	<Frame name="CharacterStatLabelTemplate" renderer="DefaultRenderer">
		<Property name="Font" value="DefaultSmall" />

		<Visual>
			<ImagerySection name="Text">
				<TextComponent color="FFEED37C" horzAlign="LEFT" />
			</ImagerySection>
			<StateImagery name="Enabled">
				<Layer>
					<Section section="Text" />
				</Layer>
			</StateImagery>
			<StateImagery name="Disabled">
				<Layer>
					<Section section="Text" />
				</Layer>
			</StateImagery>
		</Visual>
		<Area>
			<Size><AbsDimension x="0" y="44" /></Size>
		</Area>
	</Frame>

	<Frame name="CharacterStatValueTemplate" renderer="DefaultRenderer">
		<Property name="Font" value="DefaultSmall" />

		<Visual>
			<ImagerySection name="Text">
				<TextComponent color="FFFFFFFF" horzAlign="RIGHT" />
			</ImagerySection>
			<StateImagery name="Enabled">
				<Layer>
					<Section section="Text" />
				</Layer>
			</StateImagery>
			<StateImagery name="Disabled">
				<Layer>
					<Section section="Text" />
				</Layer>
			</StateImagery>
		</Visual>
		<Area>
			<Size><AbsDimension x="0" y="44" /></Size>
		</Area>
	</Frame>
	
	<Frame name="CharacterWindow" renderer="DefaultRenderer" parent="GameParent">
		<Property name="Visible" value="False" />

		<Visual>
			<ImagerySection name="Background">
				<BorderComponent texture="Interface/GameUI/fg4_borders_01_03.htex" borderSize="250" />
			</ImagerySection>
			<StateImagery name="Enabled">
				<Layer>
					<Section section="Background" />
				</Layer>
			</StateImagery>
		</Visual>

		<Area>
			<Size><AbsDimension x="960" y="1280" /></Size>
			<Anchor point="LEFT" offset="48" />
			<Anchor point="V_CENTER" />
		</Area>

        <Scripts>
            <OnLoad>
                return function(this)
                    CharacterWindow_OnLoad(this)
                end
            </OnLoad>
        </Scripts>

		<Frame name="CharacterWindowTitle" inherits="TitleBar">
			<Property name="Text" value="CHARACTER" />

			<Area>
				<Anchor point="TOP" offset="62" />
				<Anchor point="LEFT" offset="48" />
				<Anchor point="RIGHT" offset="-48" />
			</Area>
		</Frame>

		<Frame name="CharacterWindowAttributeFrame" renderer="DefaultRenderer">
			<Visual>
				<ImagerySection name="Border">
					<BorderComponent texture="Interface/GameUI/fg4_borders_01_19.htex" borderSize="25" />
				</ImagerySection>
				<StateImagery name="Enabled">
					<Layer>
						<Section section="Border" />
					</Layer>
				</StateImagery>
			</Visual>

			<Area>
				<Anchor point="TOP" relativePoint="BOTTOM" relativeTo="CharacterWindowTitle" offset="5" />
				<Anchor point="LEFT" offset="48" />
				<Anchor point="RIGHT" offset="-48" />
				<Anchor point="BOTTOM" offset="-48" />
			</Area>

			<Frame name="CharacterStatLabel0" inherits="CharacterStatLabelTemplate" id="0">
				<Property name="Text" value="STAMINA" />

				<Area>
					<Anchor point="TOP" offset="32" />
					<Anchor point="LEFT" offset="24" />
					<Anchor point="RIGHT" offset="-8" />
				</Area>
			</Frame>

			<Frame name="CharacterStat0" inherits="CharacterStatValueTemplate" id="0">
				<Property name="Text" value="0" />

				<Area>
					<Anchor point="TOP" relativeTo="CharacterStatLabel0" />
					<Anchor point="LEFT" offset="8" />
					<Anchor point="RIGHT" offset="-24" />
				</Area>
			</Frame>
			
			<Frame name="CharacterStatLabel1" inherits="CharacterStatLabelTemplate" id="1">
				<Property name="Text" value="STRENGTH" />

				<Area>
					<Anchor point="TOP" offset="8" relativePoint="BOTTOM" relativeTo="CharacterStatLabel0" />
					<Anchor point="LEFT" offset="24" />
					<Anchor point="RIGHT" offset="-8" />
				</Area>
			</Frame>

			<Frame name="CharacterStat1" inherits="CharacterStatValueTemplate" id="1">
				<Property name="Text" value="0" />

				<Area>
					<Anchor point="TOP" relativeTo="CharacterStatLabel1" />
					<Anchor point="LEFT" offset="8" />
					<Anchor point="RIGHT" offset="-24" />
				</Area>
			</Frame>

			<Frame name="CharacterStatLabel2" inherits="CharacterStatLabelTemplate" id="2">
				<Property name="Text" value="AGILITY" />

				<Area>
					<Anchor point="TOP" offset="8" relativePoint="BOTTOM" relativeTo="CharacterStatLabel1" />
					<Anchor point="LEFT" offset="24" />
					<Anchor point="RIGHT" offset="-8" />
				</Area>
			</Frame>

			<Frame name="CharacterStat2" inherits="CharacterStatValueTemplate" id="2">
				<Property name="Text" value="0" />

				<Area>
					<Anchor point="TOP" relativeTo="CharacterStatLabel2" />
					<Anchor point="LEFT" offset="8" />
					<Anchor point="RIGHT" offset="-24" />
				</Area>
			</Frame>

			<Frame name="CharacterStatLabel3" inherits="CharacterStatLabelTemplate" id="3">
				<Property name="Text" value="INTELLECT" />

				<Area>
					<Anchor point="TOP" offset="8" relativePoint="BOTTOM" relativeTo="CharacterStatLabel2" />
					<Anchor point="LEFT" offset="24" />
					<Anchor point="RIGHT" offset="-8" />
				</Area>
			</Frame>

			<Frame name="CharacterStat3" inherits="CharacterStatValueTemplate" id="3">
				<Property name="Text" value="0" />

				<Area>
					<Anchor point="TOP" relativeTo="CharacterStatLabel3" />
					<Anchor point="LEFT" offset="8" />
					<Anchor point="RIGHT" offset="-24" />
				</Area>
			</Frame>

			<Frame name="CharacterStatLabel4" inherits="CharacterStatLabelTemplate" id="4">
				<Property name="Text" value="SPIRIT" />

				<Area>
					<Anchor point="TOP" offset="8" relativePoint="BOTTOM" relativeTo="CharacterStatLabel3" />
					<Anchor point="LEFT" offset="24" />
					<Anchor point="RIGHT" offset="-8" />
				</Area>
			</Frame>

			<Frame name="CharacterStat4" inherits="CharacterStatValueTemplate" id="4">
				<Property name="Text" value="0" />

				<Area>
					<Anchor point="TOP" relativeTo="CharacterStatLabel4" />
					<Anchor point="LEFT" offset="8" />
					<Anchor point="RIGHT" offset="-24" />
				</Area>
			</Frame>
		</Frame>
	</Frame>
</UiLayout>

=== Futuray-pgm/mmo-data/Interface/GameUI/QuestFrame.xml
<?xml version="1.0" ?>
<UiLayout xmlns="http://www.w3schools.com/Ui" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com/Ui.xsd file:///F:/mmo/data/client/Interface/Ui.xsd">
	<Script file="QuestFrame.lua" />

	<Font name="QuestTitleFont" file="Fonts/arbutusslab-regular.ttf" size="30" outline="0" />
	<Font name="QuestFont" file="Fonts/arbutusslab-regular.ttf" size="24" outline="0" />

    <Frame name="QuestFramePanelTemplate" renderer="DefaultRenderer" setAllPoints="true">
        <Property name="Visible" value="False" />

        <Visual>
            <ImagerySection name="Frame">
                <BorderComponent texture="Interface/GlueUI/FrameBorder01.htex" border="48" tint="FFD8C6A8">
                    <Area><Inset right="96" top="8" left="8" bottom="8" /></Area>
                </BorderComponent>
                <BorderComponent texture="Interface/GameUI/fg4_borders_01_19.htex" borderSize="25" />
            </ImagerySection>
            <StateImagery name="Enabled">
                <Layer>
                    <Section section="Frame" />
                </Layer>
            </StateImagery>
            <StateImagery name="Disabled">
                <Layer>
                    <Section section="Frame" />
                </Layer>
            </StateImagery>
        </Visual>
    </Frame>

    <Frame name="QuestMenuButtonTemplate" type="Button" renderer="ButtonRenderer">
        <Property name="Font" value="QuestFont" />
        <Property name="Icon" />

        <Visual>
			<ImagerySection name="BackgroundHighlight">
				<ImageComponent texture="Interface/GlueUI/ListItemHighlight.htex" tint="7FFACC12" tiling="VERTICAL">
					<Area><Inset all="4" /></Area>
				</ImageComponent>
			</ImagerySection>
			<ImagerySection name="BackgroundPressed">
				<ImageComponent texture="Interface/GlueUI/ListItemHighlight.htex" tint="7FFACC12" tiling="VERTICAL">
					<Area><Inset top="8" bottom="0" left="4" right="4" /></Area>
				</ImageComponent>
			</ImagerySection>
            <ImagerySection name="Icon">
                <ImageComponent tiling="NONE">
                    <Area><Inset all="6" /><Size><AbsDimension x="48" y="48" /></Size></Area>
					<PropertyValue property="Icon" />
                </ImageComponent>
            </ImagerySection>
			<ImagerySection name="TextDefault">
				<TextComponent color="FF100500" horzAlign="LEFT" vertAlign="CENTER">
					<Area><Inset left="64" /></Area>
                </TextComponent>
			</ImagerySection>
			<ImagerySection name="TextHovered">
				<TextComponent color="FFFFFFFF" horzAlign="LEFT" vertAlign="CENTER">
					<Area><Inset left="64" /></Area>
                </TextComponent>
			</ImagerySection>
			<ImagerySection name="TextPressed">
				<TextComponent color="FFCDCDCD" horzAlign="LEFT" vertAlign="CENTER">
					<Area><Inset left="64" /></Area>
                </TextComponent>
			</ImagerySection>
			
			<StateImagery name="Normal">
				<Layer>
                    <Section section="Icon" />
					<Section section="TextDefault" />
				</Layer>
			</StateImagery>
			<StateImagery name="Hovered">
				<Layer>
					<Section section="BackgroundHighlight" />
                    <Section section="Icon" />
					<Section section="TextHovered" />
				</Layer>
			</StateImagery>
			<StateImagery name="Pushed">
				<Layer>
					<Section section="BackgroundPressed" />
                    <Section section="Icon" />
					<Section section="TextPressed" />
				</Layer>
			</StateImagery>
			<StateImagery name="Disabled">
				<Layer>
                    <Section section="Icon" />
					<Section section="TextDefault" />
				</Layer>
			</StateImagery>
		</Visual>
		<Area>
			<Size><AbsDimension y="60" /></Size>
		</Area>
    </Frame>

	<Frame name="QuestFrame" inherits="SidePanelTemplate" parent="GameParent">
		<Property name="Visible" value="False" />

        <Frame name="QuestFramePanels">
            <Area>
                <Anchor point="TOP" relativePoint="BOTTOM" relativeTo="QuestFrame_SidePanelTitleBar" />
                <Anchor point="LEFT" offset="24" />
                <Anchor point="RIGHT" offset="-24" />
                <Anchor point="BOTTOM" offset="-24" />
            </Area>

            <Frame name="QuestFrameGreetingPanel" inherits="QuestFramePanelTemplate" setAllPoints="true">
                <Frame name="GreetingPanelScrollBar" inherits="VerticalScrollBar">
                    <Property name="Enabled" value="false" />

                    <Area>
                        <Anchor point="RIGHT" offset="0" />
                        <Anchor point="TOP" offset="0" />
                        <Anchor point="BOTTOM" offset="0" />
                    </Area>
                </Frame>

                <Frame name="GreetingText" inherits="TextSmall">
                    <Property name="Font" value="QuestFont" />
                    <Property name="TextColor" value="FF100500" />

                    <Area>
                        <Anchor point="TOP" offset="32" />
                        <Anchor point="LEFT" offset="32" />
                        <Anchor point="RIGHT" relativePoint="LEFT" relativeTo="GreetingPanelScrollBar" offset="-16" />
                    </Area>
                </Frame>

                <Frame name="QuestFrameAvailableQuests" inherits="TextSmall">
                    <Property name="Text" value="AVAILABLE_QUESTS" />
                    <Property name="TextColor" value="FF100500" />
                    <Property name="Font" value="QuestTitleFont" />

                    <Area>
                        <Anchor point="TOP" relativePoint="BOTTOM" relativeTo="GreetingText" offset="32" />
                        <Anchor point="LEFT" offset="32" />
                        <Anchor point="RIGHT" relativePoint="LEFT" relativeTo="GreetingPanelScrollBar" offset="-16" />
                    </Area>
                </Frame>
                
                <Frame name="AvailableQuestList">
                    <Area>
                        <Anchor point="TOP" relativePoint="BOTTOM" relativeTo="QuestFrameAvailableQuests" offset="8" />
                        <Anchor point="LEFT" offset="32" />
                        <Anchor point="RIGHT" relativePoint="LEFT" relativeTo="GreetingPanelScrollBar" offset="-16" />
                        <Anchor point="BOTTOM" offset="-16" />
                    </Area>
                </Frame>
            </Frame>

            <Frame name="QuestFrameDetailPanel" inherits="QuestFramePanelTemplate" setAllPoints="true">
            
            </Frame>
        </Frame>
        
        <Scripts>
            <OnLoad>
                return function(this)
                    QuestFrame_OnLoad(this);
                end
            </OnLoad>
			<OnShow>
				return function(this)
					QuestFrame_OnShow(this);
				end
			</OnShow>
        </Scripts>

    </Frame>
</UiLayout>

=== Futuray-pgm/mmo-data/Interface/GameUI/InventoryFrame.xml
<?xml version="1.0" ?>
<UiLayout xmlns="http://www.w3schools.com/Ui" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com/Ui.xsd file:///F:/mmo/data/client/Interface/Ui.xsd">
	<Script file="InventoryFrame.lua" />
	
	<Frame name="MoneyText" renderer="DefaultRenderer">
		<Property name="Font" value="DefaultSmall" />

		<Visual>
			<ImagerySection name="Text">
				<TextComponent color="FFFFFFFF" horzAlign="RIGHT" vertAlign="TOP" />
			</ImagerySection>
			<StateImagery name="Enabled">
				<Layer>
					<Section section="Text" />
				</Layer>
			</StateImagery>
			<StateImagery name="Disabled">
				<Layer>
					<Section section="Text" />
				</Layer>
			</StateImagery>
		</Visual>
		<Area>
			<Size><AbsDimension x="0" y="44" /></Size>
		</Area>
	</Frame>

    <Frame name="InventoryFrame" renderer="DefaultRenderer" parent="GameParent">
		<Property name="Visible" value="False" />
		
		<Visual>
			<ImagerySection name="Background">
				<BorderComponent texture="Interface/GameUI/fg4_borders_01_03.htex" borderSize="250" />
			</ImagerySection>
			<StateImagery name="Enabled">
				<Layer>
					<Section section="Background" />
				</Layer>
			</StateImagery>
		</Visual>

		<Area>
			<Size><AbsDimension x="960" y="1280" /></Size>
			<Anchor point="BOTTOM" offset="-64" />
			<Anchor point="RIGHT" offset="-64" />
		</Area>

		<Frame name="PlayerMoney" renderer="DefaultRenderer">
			<Property name="Font" value="SmallLabelFont" />

			<Visual>
				<ImagerySection name="Border">
					<BorderComponent texture="Interface/GameUI/fg4_borders_01_19.htex" borderSize="25" />
				</ImagerySection>
				<ImagerySection name="Text">
					<TextComponent />
				</ImagerySection>
				<StateImagery name="Enabled">
					<Layer>
						<Section section="Border" />
						<Section section="Text" />
					</Layer>
				</StateImagery>
			</Visual>

			<Area>
				<Anchor point="BOTTOM" offset="-48" />
				<Anchor point="LEFT" offset="48" />
				<Anchor point="RIGHT" offset="-48" />
				<Size><AbsDimension x="0" y="72" /></Size>
			</Area>

			<Frame name="CopperText" inherits="MoneyText">
				<Area>
					<Anchor point="BOTTOM" offset="-8" />
					<Anchor point="RIGHT" offset="-16" />
					<Anchor point="TOP" offset="8" />
					<Size><AbsDimension x="100" y="72" /></Size>
				</Area>
			</Frame>

			<Frame name="SilverText" inherits="MoneyText">
				<Area>
					<Anchor point="BOTTOM" offset="-8" />
					<Anchor point="RIGHT" offset="-16" relativeTo="CopperText" relativePoint="LEFT" />
					<Anchor point="TOP" offset="8" />
					<Size><AbsDimension x="100" y="72" /></Size>
				</Area>
			</Frame>
			
			<Frame name="GoldText" inherits="MoneyText">
				<Area>
					<Anchor point="BOTTOM" offset="-8" />
					<Anchor point="RIGHT" offset="-16" relativeTo="SilverText" relativePoint="LEFT" />
					<Anchor point="TOP" offset="8" />
					<Size><AbsDimension x="100" y="72" /></Size>
				</Area>
			</Frame>

			<Scripts>
				<OnShow>
					return function(self)
						InventoryFrame_UpdateMoney(InventoryFrame);
					end
				</OnShow>
			</Scripts>
		</Frame>
	</Frame>
</UiLayout>

=== Futuray-pgm/mmo-data/Interface/GlueUI/CharCreate.xml
<?xml version="1.0"?>
<UiLayout xmlns="http://mmo-dev.net/ui" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://mmo-dev.net/ui UI.xsd">
	<Script file="CharCreate.lua" />

	<!-- This is the character selection screen frame. It covers the whole screen. -->
	<Frame name="CharCreate" parent="GlueParent" setAllPoints="true" renderer="DefaultRenderer">
		<Property name="Visible" value="false" />

		<!-- For now, only a placeholder image is rendered in the background -->
		<Visual>
			<ImagerySection name="Background">
				<ImageComponent texture="Interface/GlueUI/BackgroundPH.htex" tiling="NONE" />
			</ImagerySection>
			<StateImagery name="Enabled">
				<Layer>
					<Section section="Background" />
				</Layer>
			</StateImagery>
		</Visual>
		
		<Frame name="CharCreateModel" type="Model" setAllPoints="true" renderer="ModelRenderer">
			<Property name="Visible" value="false" />
			<Property name="ModelFile" value="Models/Cube/Cube.hmsh" />
		</Frame>
		
		<Frame renderer="DefaultRenderer">
			<Area>
				<Anchor point="LEFT"/>
				<Anchor point="RIGHT"/>
				<Anchor point="BOTTOM"/>
				<Size>
					<AbsDimension y="200" />
				</Size>
			</Area>
			<Visual>
				<ImagerySection name="Background">
					<ImageComponent texture="Interface/GlueUI/GradientBlack.htex" tiling="HORZ" />
				</ImagerySection>

				<StateImagery name="Enabled">
					<Layer>
						<Section section="Background" />
					</Layer>
				</StateImagery>
			</Visual>

			<Frame name="CharCreateSubmitButton" inherits="GlueButtonPrimary">
				<Property name="Text" value="CREATE_CHARACTER" />
				<Area>
					<Anchor point="BOTTOM" offset="-24" />
					<Anchor point="H_CENTER" />
				</Area>
			</Frame>
			
			<Frame name="NewCharacterNameBox" inherits="GlueTextField">
				<Area>
					<Anchor point="BOTTOM" relativePoint="TOP" relativeTo="CharCreateSubmitButton" offset="-8" />
					<Anchor point="H_CENTER" />
				</Area>
			</Frame>

			<Frame name="CancelCharCreationButton" inherits="GlueButton">
				<Property name="Text" value="CANCEL" />
				<Area>
					<Anchor point="RIGHT" offset="-24" />
					<Anchor point="BOTTOM" offset="-24" />
				</Area>
			</Frame>
		</Frame>
	</Frame>
</UiLayout>

=== Futuray-pgm/mmo-data/Interface/GameUI/MoneyFrame.xml
<?xml version="1.0" ?>
<UiLayout xmlns="http://www.w3schools.com/Ui" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com/Ui.xsd file:///F:/mmo/data/client/Interface/Ui.xsd">
	<Script file="MoneyFrame.lua" />
	
    <Frame name="MoneyFrameTemplate">		
		<Area>
			<Size><AbsDimension x="540" y="96" /></Size>
			<Anchor point="RIGHT" offset="-64" />
			<Anchor point="BOTTOM" offset="-64" />
		</Area>

        <Frame name="CopperButton" renderer="DefaultRenderer">
            <Property name="Text" value="0" />

            <Area>
                <Size><AbsDimension x="96" y="96" /></Size>
                <Anchor point="RIGHT" offset="0" />
                <Anchor point="BOTTOM" offset="0" />
                <Anchor point="TOP" offset="0" />
            </Area>
        </Frame>
        
        <Frame name="SilverButton" renderer="DefaultRenderer">
            <Property name="Text" value="0" />
            
            <Area>
                <Size><AbsDimension x="96" y="96" /></Size>
                <Anchor point="RIGHT" relativeTo="CopperButton" relativePoint="LEFT" offset="0" />
                <Anchor point="BOTTOM" offset="0" />
                <Anchor point="TOP" offset="0" />
            </Area>
        </Frame>
        
        <Frame name="GoldButton" renderer="DefaultRenderer">
            <Property name="Text" value="0" />

            <Area>
                <Size><AbsDimension x="96" y="96" /></Size>
                <Anchor point="RIGHT" relativeTo="SilverButton" relativePoint="LEFT" offset="0" />
                <Anchor point="BOTTOM" offset="0" />
                <Anchor point="TOP" offset="0" />
            </Area>
        </Frame>
	</Frame>
</UiLayout>

=== Futuray-pgm/mmo-data/Interface/GameUI/GameTemplates.xml
<?xml version="1.0" ?>
<UiLayout xmlns="http://www.w3schools.com/Ui" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com/Ui.xsd file:///F:/mmo/data/client/Interface/Ui.xsd">
	<Frame name="TitleBar" renderer="DefaultRenderer">
		<Property name="Font" value="DefaultHeader" />

		<Visual>
			<ImagerySection name="Background">
				<BorderComponent texture="Interface/GameUI/Borders_01_07.htex" borderSize="24" />
				<TextComponent color="FFEED37C" horzAlign="CENTER">
					<Area><Inset all="16" /></Area>
				</TextComponent>
			</ImagerySection>
			<StateImagery name="Enabled">
				<Layer>
					<Section section="Background" />
				</Layer>
			</StateImagery>
		</Visual>

		<Area>
			<Size><AbsDimension x="1000" y="90" /></Size>
		</Area>
	</Frame>
</UiLayout>
