=== Futuray-pgm/mmo-data/Interface/Ui.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="http://www.w3schools.com/Ui"
    elementFormDefault="qualified"
    xmlns="http://www.w3schools.com/Ui"
    xmlns:mstns="http://www.w3schools.com/Ui.xsd"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
>
	<xs:simpleType name="FrameRendererType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="DefaultRenderer" />
			<xs:enumeration value="ButtonRenderer" />
			<xs:enumeration value="TextfieldRenderer" />
			<xs:enumeration value="ModelRenderer" />
			<xs:enumeration value="WorldRenderer" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="AnchorPointType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="LEFT" />
			<xs:enumeration value="TOP" />
			<xs:enumeration value="RIGHT" />
			<xs:enumeration value="BOTTOM" />
			<xs:enumeration value="H_CENTER" />
			<xs:enumeration value="V_CENTER" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="TilingType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="NONE" />
			<xs:enumeration value="HORZ" />
			<xs:enumeration value="VERT" />
			<xs:enumeration value="BOTH" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="HorzAlignType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="LEFT" />
			<xs:enumeration value="CENTER" />
			<xs:enumeration value="RIGHT" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="VertAlignType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="TOP" />
			<xs:enumeration value="CENTER" />
			<xs:enumeration value="BOTTOM" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="PropertyType">
		<xs:attribute name="name" use="required" type="xs:string" />
		<xs:attribute name="value" use="optional" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="BorderComponentType">
		<xs:sequence minOccurs="0" maxOccurs="1">
			<xs:element name="Area" type="AreaComponentType" maxOccurs="1" />
		</xs:sequence>

		<xs:attribute name="texture" use="optional" type="xs:string" />
		<xs:attribute name="borderSize" use="required" type="xs:decimal" />
	</xs:complexType>

	<xs:complexType name="ImageComponentType">
		<xs:sequence minOccurs="0" maxOccurs="1">
			<xs:element name="Area" type="AreaComponentType" maxOccurs="1" />
		</xs:sequence>

		<xs:attribute name="texture" use="optional" type="xs:string" />
		<xs:attribute name="tint" use="optional" type="xs:string" default="ffffffff" />
		<xs:attribute name="tiling" use="optional" type="TilingType" default="NONE" />
	</xs:complexType>

	<xs:complexType name="TextComponentType">
		<xs:sequence minOccurs="0" maxOccurs="1">
			<xs:element name="Area" type="AreaComponentType" maxOccurs="1" />
		</xs:sequence>

		<xs:attribute name="color" use="optional" type="xs:string" default="ffffffff" />
		<xs:attribute name="horzAlign" use="optional" type="HorzAlignType" default="LEFT" />
		<xs:attribute name="vertAlign" use="optional" type="VertAlignType" default="TOP" />
	</xs:complexType>

	<xs:complexType name="ImagerySectionType">
		<xs:sequence>
			<xs:choice maxOccurs="unbounded">
				<xs:element name="BorderComponent" type="BorderComponentType" />
				<xs:element name="ImageComponent" type="ImageComponentType" />
				<xs:element name="TextComponent" type="TextComponentType" />
			</xs:choice>
		</xs:sequence>
		<xs:attribute name="name" use="required" type="xs:string" />
	</xs:complexType>
	
	<xs:complexType name="SectionType">
		<xs:attribute name="section" use="required" type="xs:string" />
	</xs:complexType>
	
	<xs:complexType name="LayerType">
		<xs:sequence>
			<xs:element name="Section" maxOccurs="unbounded" minOccurs="1" type="SectionType" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="StateImageryType">
		<xs:sequence maxOccurs="unbounded">
			<xs:element name="Layer" type="LayerType" minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>

		<xs:attribute name="name" use="required" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="VisualType">
		<xs:sequence minOccurs="0">
			<xs:choice maxOccurs="unbounded">
				<xs:element name="ImagerySection" maxOccurs="unbounded" type="ImagerySectionType" />
				<xs:element name="StateImagery" maxOccurs="unbounded" type="StateImageryType" />
			</xs:choice>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="SizeType">
		<xs:sequence>
			<xs:element name="AbsDimension">
				<xs:complexType>
					<xs:attribute name="x" use="optional" type="xs:decimal" />
					<xs:attribute name="y" use="optional" type="xs:decimal" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="AnchorType">
		<xs:attribute name="point" use="required" type="AnchorPointType" />
		<xs:attribute name="targetPoint" use="optional" type="AnchorPointType" />
		<xs:attribute name="relativeTo" use="optional" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="InsetType">
		<xs:attribute name="all" use="optional" type="xs:decimal" />
		<xs:attribute name="left" use="optional" type="xs:decimal" />
		<xs:attribute name="top" use="optional" type="xs:decimal" />
		<xs:attribute name="right" use="optional" type="xs:decimal" />
		<xs:attribute name="bottom" use="optional" type="xs:decimal" />
	</xs:complexType>

	<xs:complexType name="AreaComponentType">
		<xs:sequence>
			<xs:choice>
				<xs:element name="Inset" type="InsetType" />
			</xs:choice>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="AreaType">
		<xs:sequence>
			<xs:choice>
				<xs:element name="Size" type="SizeType" maxOccurs="1" />
				<xs:element name="Anchor" type="AnchorType" maxOccurs="6" />
			</xs:choice>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="FrameType">
		<xs:sequence>
			<xs:choice maxOccurs="unbounded">
				<xs:element name="Property" type="PropertyType" maxOccurs="unbounded" />
				<xs:element name="Visual" type="VisualType" maxOccurs="1" />
				<xs:element name="Area" maxOccurs="1" type="AreaType" />
				<xs:element name="Events" maxOccurs="1"  />
			</xs:choice>
		</xs:sequence>

		<xs:attribute name="name" type="xs:string" use="required" />
		<xs:attribute name="renderer" type="FrameRendererType" use="optional" />
	</xs:complexType>

	<xs:element name="Frame" type="FrameType" />

	<xs:element name="UiLayout">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Script" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="file" type="xs:string" use="required" />
					</xs:complexType>
				</xs:element>
				<xs:element ref="Frame" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Futuray-pgm/mmo-data/Interface/GameUI/TargetFrame.xml
<?xml version="1.0" ?>
<UiLayout xmlns="http://www.w3schools.com/Ui" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com/Ui.xsd file:///F:/mmo/data/client/Interface/Ui.xsd">
	<Script file="TargetFrame.lua" />

    <Frame name="TargetFrame" parent="GameParent">
		<Area>
			<Size>
				<AbsDimension x="440" y="128" />
				<Anchor point="LEFT" relativePoint="H_CENTER" offset="32" />
				<Anchor point="BOTTOM" relativeTo="GameMenuBar" relativePoint="TOP" offset="-384" />
			</Size>
		</Area>

		<Frame name="TargetName" inherits="TextSmall">
			<Property name="Text" value="Target Name" />
			<Area>
				<Anchor point="LEFT" />
				<Anchor point="RIGHT" />
				<Anchor point="TOP" />
				<Size><AbsDimension y="42" /></Size>
			</Area>
		</Frame>

		<Frame name="TargetHealthBar" type="ProgressBar">
			<Property name="Progress" value="0.12783" />
			<Property name="Text" value="0%" />
			<Property name="Font" value="DefaultSmall" />

			<Area>
				<Anchor point="LEFT" />
				<Anchor point="RIGHT" />
				<Anchor point="TOP" relativeTo="TargetName" relativePoint="BOTTOM" />
				<Size><AbsDimension y="32" /></Size>
			</Area>

			<Visual>
				<ImagerySection name="Caption">
					<TextComponent color="FFFFFFFF" horzAlign="CENTER" vertAlign="CENTER" />
				</ImagerySection>
				<ImagerySection name="Background">
					<BorderComponent texture="Interface/fg4_borders_01_33.htex" borderSize="5" />
				</ImagerySection>
				<ImagerySection name="Border">
					<BorderComponent texture="Interface/GameUI/fg4_borders_insetBlack.htex" borderSize="24" />
				</ImagerySection>
				<ImagerySection name="Progress">
					<ImageComponent texture="Interface/fg4_gradientWhiteV1_result.htex" tiling="HORZ" tint="FF00FF00">
						<Area><Inset all="8" /></Area>
					</ImageComponent>
				</ImagerySection>

				<StateImagery name="Enabled">
					<Layer>
						<Section section="Background" />
					</Layer>
				</StateImagery>
				<StateImagery name="Disabled">
					<Layer>
						<Section section="Background" />
					</Layer>
				</StateImagery>
				<StateImagery name="Progress">
					<Layer>
						<Section section="Progress" />
					</Layer>
				</StateImagery>
				<StateImagery name="Overlay">
					<Layer>
						<Section section="Border" />
						<Section section="Caption" />
					</Layer>
				</StateImagery>
			</Visual>
		</Frame>

		<Frame name="TargetManaBar" type="ProgressBar">
			<Property name="Progress" value="0.12783" />
			<Property name="Font" value="DefaultSmall" />

			<Area>
				<Anchor point="LEFT" />
				<Anchor point="RIGHT" />
				<Anchor point="TOP" relativePoint="BOTTOM" relativeTo="TargetHealthBar" />
				<Size><AbsDimension y="32" /></Size>
			</Area>

			<Visual>
				<ImagerySection name="Caption">
					<TextComponent color="FFFFFFFF" horzAlign="CENTER" vertAlign="CENTER" />
				</ImagerySection>
				<ImagerySection name="Background">
					<BorderComponent texture="Interface/fg4_borders_01_33.htex" borderSize="5" />
				</ImagerySection>
				<ImagerySection name="Border">
					<BorderComponent texture="Interface/GameUI/fg4_borders_insetBlack.htex" borderSize="24" />
				</ImagerySection>
				<ImagerySection name="Progress">
					<ImageComponent texture="Interface/fg4_gradientWhiteV1_result.htex" tiling="HORZ" tint="FF0000FF">
						<Area><Inset all="8" /></Area>
					</ImageComponent>
				</ImagerySection>

				<StateImagery name="Enabled">
					<Layer>
						<Section section="Background" />
					</Layer>
				</StateImagery>
				<StateImagery name="Disabled">
					<Layer>
						<Section section="Background" />
					</Layer>
				</StateImagery>
				<StateImagery name="Progress">
					<Layer>
						<Section section="Progress" />
					</Layer>
				</StateImagery>
				<StateImagery name="Overlay">
					<Layer>
						<Section section="Border" />
						<Section section="Caption" />
					</Layer>
				</StateImagery>
			</Visual>
		</Frame>

        <Frame name="TargetAuraButton1" inherits="AuraBarButtonTemplate" id="1">
            <Area>
                <Anchor point="LEFT" offset="0" />
                <Anchor point="TOP" relativePoint="BOTTOM" offset="0" />
				<Size><AbsDimension x="96" y="96" /></Size>
            </Area>
			<Scripts>
				<OnLoad>
					return function(this)
					end
				</OnLoad>
				<OnUpdate>
					return function(this, elapsed)
					end
				</OnUpdate>
			</Scripts>
        </Frame>
        
        <Frame name="TargetAuraButton2" inherits="AuraBarButtonTemplate" id="2">
            <Area>
                <Anchor point="LEFT" relativeTo="TargetAuraButton1" relativePoint="RIGHT" offset="0" />
                <Anchor point="TOP" relativeTo="TargetAuraButton1" />
				<Size><AbsDimension x="96" y="96" /></Size>
            </Area>
			<Scripts>
				<OnLoad>
					return function(this)
					end
				</OnLoad>
				<OnUpdate>
					return function(this, elapsed)
					end
				</OnUpdate>
			</Scripts>
        </Frame>
        
        <Frame name="TargetAuraButton3" inherits="AuraBarButtonTemplate" id="3">
            <Area>
                <Anchor point="LEFT" relativeTo="TargetAuraButton2" relativePoint="RIGHT" offset="0" />
                <Anchor point="TOP" relativeTo="TargetAuraButton1" />
				<Size><AbsDimension x="96" y="96" /></Size>
            </Area>
			<Scripts>
				<OnLoad>
					return function(this)
					end
				</OnLoad>
				<OnUpdate>
					return function(this, elapsed)
					end
				</OnUpdate>
			</Scripts>
        </Frame>
        
        <Frame name="TargetAuraButton4" inherits="AuraBarButtonTemplate" id="4">
            <Area>
                <Anchor point="LEFT" relativeTo="TargetAuraButton3" relativePoint="RIGHT" offset="0" />
                <Anchor point="TOP" relativeTo="TargetAuraButton1" />
				<Size><AbsDimension x="96" y="96" /></Size>
            </Area>
			<Scripts>
				<OnLoad>
					return function(this)
					end
				</OnLoad>
				<OnUpdate>
					return function(this, elapsed)
					end
				</OnUpdate>
			</Scripts>
        </Frame>
        
        <Frame name="TargetAuraButton5" inherits="AuraBarButtonTemplate" id="5">
            <Area>
                <Anchor point="LEFT" relativeTo="TargetAuraButton4" relativePoint="RIGHT" offset="0" />
                <Anchor point="TOP" relativeTo="TargetAuraButton1" />
				<Size><AbsDimension x="96" y="96" /></Size>
            </Area>
			<Scripts>
				<OnLoad>
					return function(this)
					end
				</OnLoad>
				<OnUpdate>
					return function(this, elapsed)
					end
				</OnUpdate>
			</Scripts>
        </Frame>

		<Scripts>
			<OnLoad>
				return function(this)
					TargetFrame_OnLoad();
				end
			</OnLoad>
		</Scripts>
    </Frame>
</UiLayout>

=== Futuray-pgm/mmo-data/Interface/GameUI/PlayerFrame.xml
<?xml version="1.0" ?>
<UiLayout xmlns="http://www.w3schools.com/Ui" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="file:\\F:\mmo\data\client\Interface\Ui.xsd">
	<Script file="PlayerFrame.lua" />

    <Frame name="PlayerFrame" parent="GameParent" renderer="DefaultRenderer">
        <Area>
            <Anchor point="LEFT" offset="32" />
            <Anchor point="TOP" offset="32" />
            <Size><AbsDimension x="512" y="164" /></Size>
        </Area>

		<Visual>
			<ImagerySection name="Background">
                <BorderComponent texture="Interface/GameUI/fg4_gradientBlackCircle2.htex" borderSize="31" tint="51FFFFFF" />
            </ImagerySection>
            <StateImagery name="Enabled">
                <Layer>
                    <Section section="Background" />
                </Layer>
            </StateImagery>
            <StateImagery name="Disabled">
                <Layer>
                    <Section section="Background" />
                </Layer>
            </StateImagery>
		</Visual>

		<Frame name="PlayerPortrait" renderer="DefaultRenderer">
			<Area>
				<Anchor point="TOP" offset="5" />
				<Anchor point="LEFT" offset="5" />
				<Size><AbsDimension x="128" y="128" /></Size>
			</Area>

			<Visual>
				<ImagerySection name="Background">
					<BorderComponent texture="Interface/GameUI/fg4_slotBrownRound1_result.htex" borderSize="36" tint="FFFFFFFF" />
				</ImagerySection>
				<StateImagery name="Enabled">
					<Layer>
						<Section section="Background" />
					</Layer>
				</StateImagery>
				<StateImagery name="Disabled">
					<Layer>
						<Section section="Background" />
					</Layer>
				</StateImagery>
			</Visual>

			<Frame name="PlayerPortraitLevel" renderer="DefaultRenderer">
				<Property name="Font" value="DefaultSmall" />
				<Property name="Text" value="1" />
				<Property name="TextColor" value="FFFFFFFF" />
				
				<Visual>
					<ImagerySection name="Background">
						<ImageComponent texture="Interface/GameUI/fg4_progressbar1.htex" tiling="NONE" tint="FFFF0909" />
						<TextComponent color="$TextColor" horzAlign="CENTER" vertAlign="CENTER" />
					</ImagerySection>
					<StateImagery name="Enabled">
						<Layer>
							<Section section="Background" />
						</Layer>
					</StateImagery>
					<StateImagery name="Disabled">
						<Layer>
							<Section section="Background" />
						</Layer>
					</StateImagery>
				</Visual>

				<Area>
					<Anchor point="H_CENTER" />
					<Anchor point="BOTTOM" offset="24" />
					<Size><AbsDimension x="72" y="48" /></Size>
				</Area>
			</Frame>
		</Frame>

        <Frame name="PlayerName" inherits="TextSmall">
            <Property name="Text" value="Player" />
			<Property name="Font" value="DefaultSmallOutline" />

            <Area>
                <Anchor point="LEFT" relativePoint="RIGHT" relativeTo="PlayerPortrait" offset="10" />
                <Anchor point="RIGHT" offset="-10" />
                <Anchor point="TOP" offset="10" />
                <Size><AbsDimension y="42" /></Size>
            </Area>
        </Frame>

        <Frame name="PlayerHealthBar" type="ProgressBar">
            <Property name="Progress" value="0.12783" />
			<Property name="Font" value="DefaultSmall" />

            <Area>
                <Anchor point="LEFT" relativePoint="RIGHT" relativeTo="PlayerPortrait" offset="10" />
                <Anchor point="RIGHT" offset="-10" />
                <Anchor point="TOP" relativeTo="PlayerName" relativePoint="BOTTOM" />
                <Size><AbsDimension y="70" /></Size>
            </Area>
            
			<Visual>
				<ImagerySection name="Caption">
					<TextComponent color="FFFFFFFF" horzAlign="CENTER" vertAlign="CENTER" />
				</ImagerySection>
				<ImagerySection name="Background">
					<BorderComponent texture="Interface/fg4_borders_01_33.htex" borderSize="5" />
				</ImagerySection>
				<ImagerySection name="Border">
					<BorderComponent texture="Interface/GameUI/fg4_borders_01_07_02.htex" borderSize="55" />
				</ImagerySection>
				<ImagerySection name="Progress">
					<ImageComponent texture="Interface/fg4_gradientWhiteV1_result.htex" tiling="HORZ" tint="FF00FF00">
						<Area><Inset all="8" /></Area>
					</ImageComponent>
				</ImagerySection>

				<StateImagery name="Enabled">
					<Layer>
						<Section section="Background" />
					</Layer>
				</StateImagery>
				<StateImagery name="Disabled">
					<Layer>
						<Section section="Background" />
					</Layer>
				</StateImagery>
				<StateImagery name="Progress">
					<Layer>
						<Section section="Progress" />
					</Layer>
				</StateImagery>
				<StateImagery name="Overlay">
					<Layer>
						<Section section="Border" />
						<Section section="Caption" />
					</Layer>
				</StateImagery>
			</Visual>"
        </Frame>

		<Frame name="PlayerManaBar" type="ProgressBar">
			<Property name="Progress" value="0.12783" />
			<Property name="Font" value="DefaultSmall" />

			<Area>
				<Anchor point="LEFT" relativePoint="RIGHT" relativeTo="PlayerPortrait" offset="10" />
				<Anchor point="RIGHT" offset="-10" />
				<Anchor point="TOP" relativePoint="BOTTOM" relativeTo="PlayerHealthBar" />
				<Size><AbsDimension y="40" /></Size>
			</Area>

			<Visual>
				<ImagerySection name="Caption">
					<TextComponent color="FFFFFFFF" horzAlign="CENTER" vertAlign="CENTER" />
				</ImagerySection>
				<ImagerySection name="Background">
					<BorderComponent texture="Interface/fg4_borders_01_33.htex" borderSize="5" />
				</ImagerySection>
				<ImagerySection name="Border">
					<BorderComponent texture="Interface/GameUI/fg4_borders_insetBlackSmall.htex" borderSize="11" />
				</ImagerySection>
				<ImagerySection name="Progress">
					<ImageComponent texture="Interface/fg4_gradientWhiteV1_result.htex" tiling="HORZ">
						<Area><Inset all="8" /></Area>
					</ImageComponent>
				</ImagerySection>

				<StateImagery name="Enabled">
					<Layer>
						<Section section="Background" />
					</Layer>
				</StateImagery>
				<StateImagery name="Disabled">
					<Layer>
						<Section section="Background" />
					</Layer>
				</StateImagery>
				<StateImagery name="Progress">
					<Layer>
						<Section section="Progress" />
					</Layer>
				</StateImagery>
				<StateImagery name="Overlay">
					<Layer>
						<Section section="Border" />
						<Section section="Caption" />
					</Layer>
				</StateImagery>
			</Visual>
		</Frame>

        <Frame name="PlayerLeaderIcon" inherits="IconTemplate">
            <Property name="Visible" value="false" />
            <Property name="Icon" value="Interface/Icons/fg4_iconsGold_crown_result.htex" />

            <Area>
                <Anchor point="TOP" offset="10" />
                <Anchor point="LEFT" offset="10" />
            </Area>
        </Frame>

		<Frame name="PlayerFrameClick" setAllPoints="true">
			<Scripts>
				<OnClick>
					return function(self)
						PlayerFrame_OnClick(PlayerFrame);
					end
				</OnClick>
			</Scripts>
		</Frame>

        <Scripts>
            <OnLoad>
                return function(self)
                    PlayerFrame_OnLoad(self);
                end
            </OnLoad>
        </Scripts>
    </Frame>
</UiLayout>
